= VPDB Development Utility Commands

image:https://img.shields.io/github/license/veupathdb/util-infra-dev-tools[GitHub License]
image:https://img.shields.io/github/v/release/veupathdb/util-infra-dev-tools[GitHub Release]
image:https://img.shields.io/github/go-mod/go-version/veupathdb/util-infra-dev-tools[GitHub go.mod Go version]



.Installation
----
curl -Ls https://raw.githubusercontent.com/VEuPathDB/util-infra-dev-tools/main/scripts/install.sh | sh
----


== Tools

=== `ssh-compose`

Usage::
+
[source, shell-session]
----
$ vpdb ssh-compose --gen-example
# or
$ vpdb ssh-compose host-list.yml
----

Generates a docker compose file containing configuration for SSH tunnel
containers that may be used for stack-local containers to access external
resources that require SSH tunnelling to reach.


[IMPORTANT]
--
For security reasons, the files generated by this command *SHOULD NOT* be
committed to git, while they do not contain credentials, they do expose
information about the organization and location of internal protected resources.

Committing this information only serves to make potential attacks or system
intrusions more pointed.
--


.Help Text
[%collapsible]
====
[source, shell-session]
----
$ vpdb ssh-compose --help
Usage:
  vpdb ssh-compose [options] <hosts-list>

    Generates a docker-compose configuration file and required environment variables to access
    target hosts by tunneling through a configured server via SSH.

    If an `.env` file already exists in this project, it will be updated to add any missing
    environment variables required by the generated docker compose file.  If no `.env` file yet
    exists in this project, a new one will be generated.  See the docker compose docs for `.env`
    files for more info.

    WARNING: It is strongly advised that users review all relevant security policies before
    instantiation or use of any of the containers defined in the docker-compose config generated by
    this tool to ensure that the intended use of the tunnels established by the defined containers
    is not in violation of any security policy or policies.

Flags
  -i <arg> | --image=<arg>
      Specifies an alternative docker image to use for the SSH tunnel containers.
  --gen-example
      Generates an example host-list yaml file.
  -h | --help
      Prints this help text.

Inherited Flags
  -V
      Verbose logging.  Specify multiple times to enable more granular logging.
      1x INFO, 2x DEBUG, 3x TRACE.
  -v | --version

Arguments
  <hosts-list>
      YAML file providing mapping of hosts to dependent docker compose service names.  An example
      may be generated via the --gen-example flag.
----
====

==== Example

.docker-compose.yml
[source, yaml]
----
services:
  my-db-reader:
    ...
  my-ldap-reader:
    ...
----

.host-list.yml
[source, yaml]
----
# Each entry in the 'hosts' map is an array of container definitions that depend
# on access to that host.  The entries in the list should be the names of the
# dependent containers as defined in the primary docker-compose 'services' block
# or blocks.
#
# The 'hosts' map keys MUST be "host:port" pairs.
hosts:
  some.internal.db:1234:
  - my-db-reader
  some.internal.ldap:389:
  - my-ldap-reader
----

=== `stack use`

Usage::
+
[source, shell-session]
$ vpdb stack use [-b [backup-file-name]] [-f compose-file]... <qa|prod|latest>

Pins the tag versions for services to those in use on QA, production, or dev
systems.

This command scans given compose files for services with image declarations
using environment variables for injecting image tag versions, then sets values
for those environment variables in the `.env` file.

.Help Text
[%collapsible]
====
[source, shell-session]
----
$ vpdb stack use --help
Usage:
  vpdb stack use [options] <version>

    Updates the local .env file to pin the stack image versions to a specific set of images.

Flags
  -b [arg] | --make-backup=[arg]
      Backup .env file (if exist) before writing modifications.

      May optionally be used to specify the backup name if desired.
  -f <path> | --compose-file=<path>
      Specifies a docker compose file containing images whose versions should be pinned.
      May be provided more than once.

      If unused, then 'docker-compose.yml' will be assumed.
  -h | --help
      Prints this help text.

Inherited Flags
  -V
      Verbose logging.  Specify multiple times to enable more granular logging.
      1x INFO, 2x DEBUG, 3x TRACE.
  -v | --version

Arguments
  <version>
      Environment to mimic.

      May be one of:
      - latest
      - qa
      - prod
----
====

==== Example

.docker-compose.yml
[source, yml]
----
services:
  my-service:
    image: foobar:${FIZZ_BUZZ}
----

..env
[source, shellscript]
----
FIZZ_BUZZ=1.2.4
----

=== `vdi gen-tagger`

Generates tagger YAML lines for the VDI service stack based on the latest
published image tags.

.Help Text
[%collapsible]
====
[source, shell-session]
----
$ vpdb vdi gen-tagger --help
Usage:
  vpdb vdi gen-tagger [options]

    Generates YAML map entries for the latest VDI docker image tags and prints them on STDOUT.

Flags
  -w  | --write-versions=
      Write versions out to versions.yml file.  Command will fail if versions.yml file does not
      already exist in the current working directory.
  -h | --help
      Prints this help text.

Inherited Flags
  -V
      Verbose logging.  Specify multiple times to enable more granular logging.
      1x INFO, 2x DEBUG, 3x TRACE.
  -v | --version
----
====

== Development

This project requires Go v1.23.  Use of a Go version management tool is
suggested as this requirement is likely to change as Go itself updates.  Some
options include link:https://github.com/voidint/g[`g`] and
link:https://github.com/moovweb/gvm[`gvm`].

After cloning this repo remember to run `go mod download` to fetch the source
dependencies.
