# Each entry in the 'hosts' map is an array of container definitions that depend
# on access to that host.  The entries in the list should be the names of the
# dependent containers as defined in the primary docker-compose 'services' block
# or blocks.
#
# The 'hosts' map keys MUST be "host:port" pairs.
#
# TODO: allow wildcards that match to service entries in other docker-compose files in the project.
hosts:
  ldap.foo.bar:389:
  - some-service-name
  - some-other-service
  s3.foo.bar:9000:
  - file-service